-- Dọn dữ liệu cào / phân tích cũ (giữ PROJECTS, DATA_SOURCES, FB_SOURCES, users, workspaces).
-- Chạy: sqlcmd -S localhost -d MCFH_DB -E -i CleanupScrapeData.sql

SET NOCOUNT ON;
BEGIN TRANSACTION;

BEGIN TRY
    DELETE FROM MENTION_TAGS;
    DELETE FROM FEEDBACK_ASPECTS;
    DELETE FROM AI_ANALYSIS;
    DELETE FROM SCRAPED_FEEDBACKS;
    DELETE FROM SCRAPING_JOBS;

    DELETE FROM NOTIFICATIONS
    WHERE related_type = 'scrape_order'
       OR type IN ('scrape_order', 'scraping');

    DELETE FROM SCRAPE_ORDERS;

    DELETE FROM PAYMENTS
    WHERE type = 'scrape_order'
       OR transaction_ref LIKE 'SCRAPE-%';

    DELETE FROM NSR_SNAPSHOTS;
    DELETE FROM INFLUENCERS;
    DELETE FROM MUTED_ENTITIES;
    DELETE FROM IMPORT_FILES;
    DELETE FROM SAVED_FILTERS;

    COMMIT TRANSACTION;
    PRINT 'Cleanup scrape data: OK';
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;

SELECT 'SCRAPED_FEEDBACKS' AS tbl, COUNT(*) AS cnt FROM SCRAPED_FEEDBACKS
UNION ALL SELECT 'SCRAPING_JOBS', COUNT(*) FROM SCRAPING_JOBS
UNION ALL SELECT 'SCRAPE_ORDERS', COUNT(*) FROM SCRAPE_ORDERS
UNION ALL SELECT 'AI_ANALYSIS', COUNT(*) FROM AI_ANALYSIS
UNION ALL SELECT 'PAYMENTS(scrape)', COUNT(*) FROM PAYMENTS WHERE type = 'scrape_order';
